workflows:
  backup-notion-nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"  # every hour
          filters:
            branches:
              only:
                - SuperLucky
    jobs:
      - export-workspace
      - publish-github-release:
          requires:
            - export-workspace